# Site settings
title: Artisan de Bellechasse-Etchemins | Boutique 277
description: artisan, bijoux, chandelles, savons, article pour bain, articles pour douche, déodorants pour femmes, savons à raser, articles en cuir, décorations et plus!
keywords: Artisan bijoux, chandelles, savons, article pour bain, articles pour douche, déodorants pour femmes, chouchous, masques faciaux, baumes, gloss, savons à raser, cuir, décorations
author: Boutique 277
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
