# Site settings
title: Boutique 277 | Cadeau et Bien-Être en Bellechasse & Lac-Etchemin
description: Artisan, bijoux, chandelles, savons, article pour bain, articles pour douche, déodorants pour femmes, savons à raser, articles en cuir, décorations et plus pour la région de Bellechasse et Lac-Etchemin.
keywords: bellechasse, lac-etchemin, artisan, bijoux, chandelles, savons, article pour bain, articles pour douche, déodorants pour femmes, chouchous, masques faciaux, baumes, gloss, savons à raser, cuir, décorations
author: Boutique 277
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://boutique277.com" # the base hostname & protocol for your site
permalink: /:title
